name: Flutter Cloud Build (Android)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      build_mode:
        description: 'Modo de Compilacao'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release

jobs:
  build_android:
    name: Compilar APK na Nuvem
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Codigo
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Instalar Dependencias
        run: flutter pub get

      - name: Compilar APK Android
        run: |
          BUILD_MODE="${{ inputs.build_mode || 'debug' }}"
          echo "Compilando em modo: $BUILD_MODE"
          flutter build apk --$BUILD_MODE

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: lastro-apk-${{ inputs.build_mode || 'debug' }}
          path: build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error
